* Riak-Hadoop
Riak-Hadoop is a library for using [[http://basho.com/products/riak-overview/][Riak]] as an input/output to [[http://hadoop.apache.org/mapreduce/][Hadoop
Map/Reduce]].

** How it works
By extending =InputFormat=, =InputSplit=, =RecordReader=,
=OutputFormat= and =RecordWriter=, you can declare any valid Riak M/R
input (2i query, riak search query, list of keys, bucket) as input to
a Hadoop M/R job. The library will split the keys into partitions and
Hadoop will use the =RiakRecordReader= to load Key/Value pairs from
Riak for the =Mapper= tasks. The =Reducer= output is written back to a
configured bucket in Riak. It uses the [[https://github.com/basho/riak-java-client/][Riak-Java-Client]] to talk to Riak.

** Example?
Have a look at the
[[https://github.com/russelldb/riak-hadoop-wordcount][Riak Word Count]] example project to get started with Riak-Hadoop.

** Future
I plan to have the library load bulk data from Riak to HDFS to better
leverage Hadoop's integration with that file system.

** Feedback
Raise issues, pull requests, comments etc. as ever through GitHub, or
[[http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com][the Riak mailing list]].
